name: publish

on:
  release:
    types: [ published ]

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'

      - name: Install poetry
        run: |
          python -m pip install --upgrade pip
          pip install poetry

      - name: Install dependencies
        run: poetry install

      - name: Lint/format check
        run: poetry run ruff check && poetry run ruff format --check

      - name: Build package
        run: poetry build

      - name: Install xvfb
        run: sudo apt-get install -y xvfb

      - name: Start virtual display
        run: |
          Xvfb :99 -screen 0 1024x768x16 &
          echo "DISPLAY=:99" >> $GITHUB_ENV

      - name: Run tests
        run: |
          poetry run pytest


      - name: Attach package to release
        uses: softprops/action-gh-release@v1
        with:
          files: dist/*.whl, dist/*.tar.gz
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Publish to PyPI
        env:
          POETRY_PYPI_TOKEN_PYPI: ${{ secrets.PYPI_TOKEN }}
        run: |
          poetry publish